/**
 * The semantic token contract for new UI. Values intentionally live in
 * globals.css so existing CSS Modules and legacy classes keep working.
 */
export const DESIGN_TOKEN_NAMES = [
  "--wbm-color-bg",
  "--wbm-color-surface",
  "--wbm-color-surface-elevated",
  "--wbm-color-text",
  "--wbm-color-text-muted",
  "--wbm-color-border",
  "--wbm-color-border-muted",
  "--wbm-color-accent",
  "--wbm-color-primary",
  "--wbm-color-secondary",
  "--wbm-color-success",
  "--wbm-color-warning",
  "--wbm-color-danger",
  "--wbm-color-overlay",
  "--wbm-color-focus",
  "--wbm-font-body",
  "--wbm-font-display",
  "--wbm-font-size-body",
  "--wbm-font-size-caption",
  "--wbm-font-size-label",
  "--wbm-font-size-h1",
  "--wbm-font-size-h2",
  "--wbm-font-size-h3",
  "--wbm-font-weight-regular",
  "--wbm-font-weight-medium",
  "--wbm-font-weight-semibold",
  "--wbm-font-weight-bold",
  "--wbm-line-height-body",
  "--wbm-line-height-heading",
  "--wbm-space-1",
  "--wbm-space-2",
  "--wbm-space-3",
  "--wbm-space-4",
  "--wbm-space-5",
  "--wbm-space-6",
  "--wbm-space-7",
  "--wbm-space-8",
  "--wbm-radius-sm",
  "--wbm-radius-md",
  "--wbm-radius-lg",
  "--wbm-radius-xl",
  "--wbm-border-width",
  "--wbm-shadow-sm",
  "--wbm-shadow-md",
  "--wbm-shadow-modal",
  "--wbm-motion-fast",
  "--wbm-motion-normal",
  "--wbm-motion-slow",
  "--wbm-motion-ease",
  "--wbm-content-width",
  "--wbm-article-width",
  "--wbm-dashboard-width",
  "--wbm-reader-width",
  "--wbm-breakpoint-mobile",
  "--wbm-breakpoint-tablet",
  "--wbm-breakpoint-desktop",
] as const;

export type DesignTokenName = (typeof DESIGN_TOKEN_NAMES)[number];
