import type { EditorHelpCatalogEntry } from "@/lib/editorGuidance/helpTypes";
import { EDITOR_HELP_ACTION_IDS } from "@/lib/editorGuidance/actionIds";

const entry = (
  value: Omit<EditorHelpCatalogEntry, "locale">,
): EditorHelpCatalogEntry => ({ locale: "ja-JP", ...value });

export const EDITOR_HELP_CATALOG: readonly EditorHelpCatalogEntry[] = [
  entry({ intent: "manuscript.paste", title: "文章を貼り付ける", answer: "原稿欄の本文編集エリアへ文章を貼り付けると、通常のテキストやMarkdownを本文ブロックとして取り込めます。貼り付け時の自動構造化は原文の内容を書き換えず、見出し・段落・ページ構成を整えます。", phrases: ["文章を貼り付けたい", "原稿をペーストしたい", "本文を貼りたい"], keywords: ["貼り付け", "ペースト", "原稿"], uniqueKeywords: ["ペースト"], priority: 100, actionId: EDITOR_HELP_ACTION_IDS.manuscriptFocus, source: "editor", relatedIntents: ["smart.format", "manuscript.import"] }),
  entry({ intent: "manuscript.import", title: "原稿ファイルを読み込む", answer: "原稿欄の「ファイルを選択」からTXT・Markdown・Word・PDF・ZIPを読み込めます。読み込み後は本文編集エリアとMini Previewで内容を確認してください。", phrases: ["ファイルを読み込みたい", "wordを読み込みたい", "pdfを読み込みたい", "txtを読み込みたい"], keywords: ["読み込み", "インポート", "word", "pdf", "txt", "markdown", "zip"], uniqueKeywords: ["インポート", "word", "pdf", "txt", "zip"], priority: 99, actionId: EDITOR_HELP_ACTION_IDS.manuscriptImportFocus, source: "editor", relatedIntents: ["manuscript.paste"] }),
  entry({ intent: "smart.format", title: "自動で文章を整える", answer: "「自動で整える」は原文を創作・要約せず、章、見出し、段落、目次、ページ構成をルールベースで整えます。原稿を入れた後に1回実行し、Mini Previewで結果を確認してください。", phrases: ["自動で整えたい", "smart formatを使いたい", "章を認識させたい", "見出しを作りたい"], keywords: ["自動整形", "整える", "smart format", "章認識", "見出し"], uniqueKeywords: ["自動整形", "smart format", "章認識"], priority: 98, actionId: EDITOR_HELP_ACTION_IDS.smartFormatFocus, source: "editor", relatedIntents: ["smart.undo", "toc"] }),
  entry({ intent: "smart.undo", title: "自動整形前に戻す", answer: "Smart Formatを実行した直後は「整形前に戻す」で、実行前の状態へ1回だけ戻せます。一般的な無制限UndoやRedoではありません。", phrases: ["整形前に戻したい", "自動整形を元に戻したい", "smart formatを取り消したい"], keywords: ["整形前", "自動整形", "取り消し", "元に戻す"], uniqueKeywords: ["整形前"], priority: 97, actionId: EDITOR_HELP_ACTION_IDS.smartUndoFocus, source: "editor", relatedIntents: ["smart.format"] }),
  entry({ intent: "image.insert", title: "画像を追加する", answer: "画像は本文編集画面の追加したい位置で「＋」から画像を選ぶか、貼り付け・ドラッグ＆ドロップで追加できます。アップロードが完了し、画像がready状態になってから保存やPreviewへ進んでください。", phrases: ["画像を入れたい", "写真を入れたい", "画像を挿入したい", "写真を追加したい"], keywords: ["画像", "写真", "挿絵", "画像追加", "写真追加"], uniqueKeywords: ["挿絵", "画像追加", "写真追加"], priority: 96, actionId: EDITOR_HELP_ACTION_IDS.imageInsertOpen, source: "editor", relatedIntents: ["image.size", "image.reupload"] }),
  entry({ intent: "image.reupload", title: "未完了の画像を再アップロードする", answer: "未完了の画像ブロックを選び、「再アップロード」から同じ画像ファイルを選択してください。不要ならその画像ブロックを削除すると、保存・Previewの停止を解除できます。", phrases: ["画像を再アップロードしたい", "画像アップロードをやり直したい", "pending画像を直したい"], keywords: ["画像", "再アップロード", "pending", "画像未完了", "アップロード中断"], uniqueKeywords: ["再アップロード", "pending", "アップロード中断"], priority: 95, actionId: EDITOR_HELP_ACTION_IDS.pendingImageFocus, source: "editor", relatedIntents: ["image.insert"] }),
  entry({ intent: "image.size", title: "画像サイズを変える", answer: "本文内の画像を選択すると、small・medium・large・fullなど既存の表示サイズを変更できます。Previewで前後の文章やページ分割も確認してください。", phrases: ["画像サイズ", "画像を大きくしたい", "画像を小さくしたい", "写真サイズを変えたい"], keywords: ["画像", "写真", "サイズ", "大きく", "小さく"], uniqueKeywords: ["画像サイズ", "写真サイズ"], priority: 95, source: "editor", relatedIntents: ["image.insert"] }),
  entry({ intent: "youtube.insert", title: "YouTube動画を埋め込む", answer: "本文の挿入したい位置で「＋」を開き、「YouTube動画を埋め込む」から動画URLを入力します。保存後はPreviewで埋め込み位置と表示を確認してください。", phrases: ["youtubeを貼りたい", "動画を入れたい", "youtubeを埋め込みたい"], keywords: ["youtube", "動画", "埋め込み"], uniqueKeywords: ["youtube", "動画埋め込み"], priority: 94, actionId: EDITOR_HELP_ACTION_IDS.youtubeInsertOpen, source: "editor" }),
  entry({ intent: "text.bold", title: "文字を太字にする", answer: "本文編集エリアで文字範囲を選択し、表示される装飾ツールから太字を選びます。装飾は選択した範囲だけに保存されます。", phrases: ["文字を太字にしたい", "文章を太くしたい", "boldにしたい"], keywords: ["太字", "bold", "太く"], uniqueKeywords: ["太字", "bold"], priority: 92, source: "editor" }),
  entry({ intent: "text.color", title: "文字色を変える", answer: "本文編集エリアで文字範囲を選択し、装飾ツールの文字色から色を指定します。背景とのコントラストを保ち、Previewで読みやすさを確認してください。", phrases: ["文字色を変えたい", "文章に色を付けたい", "テキストカラーを変えたい"], keywords: ["文字色", "色を付け", "テキストカラー"], uniqueKeywords: ["文字色", "テキストカラー"], priority: 92, source: "editor" }),
  entry({ intent: "text.size", title: "本文の一部の文字サイズを変える", answer: "本文編集エリアで文字範囲を選択し、装飾ツールのサイズから小・標準・大を選べます。作品全体の文字サイズは「デザイン・公開設定」の文字サイズで変更します。", phrases: ["文字サイズを変えたい", "一部の文字を大きくしたい", "テキストサイズを変えたい"], keywords: ["文字サイズ", "テキストサイズ", "文字を大きく"], uniqueKeywords: ["文字サイズ", "テキストサイズ"], priority: 91, source: "editor", relatedIntents: ["design.font"] }),
  entry({ intent: "page.break", title: "ここでページを分ける", answer: "本文の区切りたい位置で「＋」を開き、「ページ区切り」を挿入します。章ごとに機械的に追加せず、Previewで見出しや段落のつながりを見ながら必要な位置だけに使ってください。", phrases: ["ここでページを変えたい", "改ページしたい", "次のページから始めたい"], keywords: ["改ページ", "ページ区切り", "次のページ"], uniqueKeywords: ["改ページ", "ページ区切り"], priority: 94, actionId: EDITOR_HELP_ACTION_IDS.pageBreakOpen, source: "editor" }),
  entry({ intent: "columns.insert", title: "2カラムを挿入する", answer: "本文の挿入したい位置で「＋」から2カラムを追加できます。左右にはテキスト・画像・YouTubeを配置でき、50:50・40:60・60:40の比率を選べます。", phrases: ["2カラムを入れたい", "二カラムにしたい", "左右二列にしたい", "二段組にしたい"], keywords: ["2カラム", "二カラム", "2列", "二列", "二段組", "左右"], uniqueKeywords: ["2カラム", "二カラム", "二段組"], priority: 94, actionId: EDITOR_HELP_ACTION_IDS.columnsInsertOpen, source: "editor", relatedIntents: ["columns.ratio", "columns.swap"] }),
  entry({ intent: "columns.ratio", title: "2カラムの幅を変える", answer: "2カラムブロックの比率メニューから50:50・40:60・60:40を選べます。変更後はMini PreviewとFull Previewで左右の収まりを確認してください。", phrases: ["カラム比率を変えたい", "左右の幅を変えたい", "40 60にしたい"], keywords: ["カラム比率", "50:50", "40:60", "60:40", "左右の幅"], uniqueKeywords: ["カラム比率", "50:50", "40:60", "60:40"], priority: 90, source: "editor", relatedIntents: ["columns.insert", "columns.swap"] }),
  entry({ intent: "columns.swap", title: "2カラムの左右を入れ替える", answer: "2カラムブロックの「左右を入れ替え」を選ぶと、左右の内容をまとめて交換できます。テキストや画像など各子ブロックの内容は保持されます。", phrases: ["カラムの左右を入れ替えたい", "左右を交換したい", "2カラムを反転したい"], keywords: ["左右を入れ替え", "左右を交換", "カラム反転"], uniqueKeywords: ["左右を入れ替え", "カラム反転"], priority: 90, source: "editor", relatedIntents: ["columns.insert", "columns.ratio"] }),
  entry({ intent: "paywall.insert", title: "ここから有料を設定する", answer: "本文の有料部分を始めたい位置で「＋」から「ここから有料」を挿入します。1作品につきPaywallは1個で、境界より前が無料、後ろが購入者向けになります。", phrases: ["ここから有料にしたい", "有料部分を設定したい", "続きを有料にしたい", "paywallを入れたい"], keywords: ["有料", "販売", "paywall", "ペイウォール"], uniqueKeywords: ["paywall", "ペイウォール", "ここから有料"], priority: 94, actionId: EDITOR_HELP_ACTION_IDS.paywallInsertOpen, source: "editor", relatedIntents: ["paywall.remove", "sales.external"] }),
  entry({ intent: "paywall.remove", title: "有料境界を削除する", answer: "Editor内の「ここから有料」ブロックを選び、削除操作を実行します。削除後に保存すると、その作品にはPaywall境界がない状態になります。", phrases: ["paywallを削除したい", "有料境界を消したい", "無料に戻したい"], keywords: ["paywall削除", "有料境界削除", "無料に戻す"], uniqueKeywords: ["paywall削除", "有料境界削除"], priority: 93, actionId: EDITOR_HELP_ACTION_IDS.paywallExistingFocus, source: "editor", relatedIntents: ["paywall.insert"] }),
  entry({ intent: "cover.edit", title: "表紙を変更する", answer: "Editor上段の「表紙画像」で画像を選択し、必要に応じて表紙スタイルを調整します。表紙画像はJPEG・PNG・WebPの10MBまでで、Previewで見え方を確認できます。", phrases: ["表紙を変えたい", "表紙画像", "カバーを変更したい", "表紙を編集したい"], keywords: ["表紙", "カバー", "表紙画像"], uniqueKeywords: ["表紙", "カバー", "表紙画像"], priority: 98, actionId: EDITOR_HELP_ACTION_IDS.coverFocus, source: "editor" }),
  entry({ intent: "toc", title: "目次を整える", answer: "目次はDocument Structureの章・節見出しから自動生成されます。目次文字列を直接編集するのではなく、本文の見出し構造を直すかSmart Formatを実行して更新してください。", phrases: ["目次を作りたい", "目次がおかしい", "目次を変更したい"], keywords: ["目次", "toc", "document structure"], uniqueKeywords: ["目次", "toc"], priority: 96, source: "editor", relatedIntents: ["smart.format"] }),
  entry({ intent: "save", title: "作品を保存する", answer: "上部または下部の「保存」は、現在の作品データを正式に保存します。自動保存は編集中の復元用であり、作業の区切りやPreview・公開の前には正式な保存も行ってください。", phrases: ["作品を保存したい", "今すぐ保存したい", "セーブしたい"], keywords: ["保存", "セーブ", "正式保存"], uniqueKeywords: ["セーブ", "正式保存"], priority: 93, actionId: EDITOR_HELP_ACTION_IDS.saveFocus, source: "editor", relatedIntents: ["autosave"] }),
  entry({ intent: "preview", title: "仕上がりを確認する", answer: "Mini Previewは編集中のページ構成をその場で確認する一覧です。「プレビュー」は読者に近いFull Previewを開き、表紙・目次・ページめくり・画像などを通して確認できます。", phrases: ["プレビューしたい", "出来上がりを確認したい", "読者画面を見たい", "full previewを見たい"], keywords: ["プレビュー", "preview", "出来上がり", "読者画面", "mini preview"], uniqueKeywords: ["プレビュー", "preview", "mini preview"], priority: 94, actionId: EDITOR_HELP_ACTION_IDS.previewFocus, source: "editor" }),
  entry({ intent: "publish", title: "Webブックを公開する", answer: "公開URLを設定し、保存内容を確認してから「公開」を実行するとWebブックとして読者へ公開できます。これはKindleなどのストア出版ではなく、WebBookMaker上の公開URLを発行する操作です。", phrases: ["webブックを公開したい", "urlを発行したい", "読者に見せたい", "公開する方法"], keywords: ["公開", "出版", "url発行", "読者に見せる"], uniqueKeywords: ["url発行"], priority: 91, actionId: EDITOR_HELP_ACTION_IDS.publishFocus, source: "editor", relatedIntents: ["slug", "share"] }),
  entry({ intent: "slug", title: "公開URLを設定する", answer: "「基本情報」の公開URL欄で、半角英数字とハイフンを使ってURL名を設定します。既存作品と重複する値や形式が正しくない値は使用できません。", phrases: ["urlを変えたい", "公開urlを変更したい", "url名を決めたい", "slugを変えたい"], keywords: ["公開url", "url名", "slug", "アドレス"], uniqueKeywords: ["slug", "url名", "公開url"], priority: 97, actionId: EDITOR_HELP_ACTION_IDS.slugFocus, source: "editor" }),
  entry({ intent: "autosave", title: "自動保存と復元", answer: "自動保存は、このブラウザで編集中の状態を復元するためのローカル保存です。クラウドへの正式保存とは異なるため、重要な区切りでは「保存」も実行し、原稿の手元保管も続けてください。", phrases: ["自動保存について知りたい", "途中から復元したい", "勝手に保存される"], keywords: ["自動保存", "autosave", "復元", "途中保存"], uniqueKeywords: ["自動保存", "autosave", "途中保存"], priority: 95, source: "editor", relatedIntents: ["save"] }),
  entry({ intent: "design.background", title: "ページ背景を変える", answer: "「デザイン・公開設定」の背景から、紙・アイボリー・カフェ・グリーン・ナイト・ホワイトを選べます。選択後はMini PreviewとFull Previewで本文の読みやすさを確認してください。", phrases: ["背景を変えたい", "白背景にしたい", "ページ背景色を変えたい"], keywords: ["背景", "背景色", "白背景", "ホワイト"], uniqueKeywords: ["背景", "背景色", "白背景"], priority: 89, source: "editor" }),
  entry({ intent: "design.font", title: "作品全体のフォントを変える", answer: "「デザイン・公開設定」のフォントから明朝・ゴシック・Serif・Sansを選べます。同じ場所で作品全体の文字サイズも小・中・大から調整できます。", phrases: ["フォントを変えたい", "明朝体にしたい", "ゴシック体にしたい", "全体の文字を大きくしたい"], keywords: ["フォント", "明朝", "ゴシック", "serif", "sans"], uniqueKeywords: ["フォント", "明朝", "ゴシック"], priority: 89, source: "editor", relatedIntents: ["text.size"] }),
  entry({ intent: "analytics", title: "作品の読まれ方を確認する", answer: "Analyticsでは、公開作品の閲覧数、読者が到達したページ、流入元、外部リンクのクリックなど現在記録している指標を確認できます。Editorの内容を保存・公開した後、Analytics画面から対象作品を選んでください。", phrases: ["アクセス解析", "閲覧数を見たい", "どこまで読まれたか知りたい", "analyticsを見たい"], keywords: ["analytics", "分析", "閲覧数", "アクセス", "読了率", "どこまで読まれた"], uniqueKeywords: ["analytics", "閲覧数", "読了率"], priority: 92, route: "/analytics", source: "analytics" }),
  entry({ intent: "share", title: "公開URLを共有する", answer: "公開後の作品画面や「作品を広める」画面から、公開URLのコピーやX・note・LINE・Facebook向けの共有を行えます。共有する前に公開作品を開き、正しいURLと表示内容を確認してください。", phrases: ["urlを共有したい", "urlをコピーしたい", "snsでシェアしたい", "lineで送りたい"], keywords: ["共有", "シェア", "sns", "x", "note", "line", "facebook", "urlコピー"], uniqueKeywords: ["シェア", "sns", "facebook", "urlコピー"], priority: 91, source: "help", relatedIntents: ["qr"] }),
  entry({ intent: "qr", title: "QRコードで作品を渡す", answer: "公開作品の共有画面では、その作品の公開URLからQRコードを表示し、PNG保存できます。名刺や店頭掲示に使う場合も、保存したQRコードが実際の公開作品を開くことを確認してください。", phrases: ["qrコードを作りたい", "qrを保存したい", "名刺にqrを載せたい", "店頭でqrを見せたい"], keywords: ["qr", "qrコード", "名刺", "店頭", "チラシ"], uniqueKeywords: ["qr", "qrコード"], priority: 91, source: "help", relatedIntents: ["share"] }),
  entry({ intent: "sales.external", title: "外部販売ページへ案内する", answer: "「デザイン・公開設定」の外部販売ページ名とURLに、既存の購入先を設定できます。これは本文をPaywallで区切る機能とは別で、WebBookMaker外の販売・応援ページへのリンクを作品に表示する設定です。", phrases: ["販売urlを設定したい", "購入先を設定したい", "外部販売ページを載せたい", "画像を販売したい", "有料url"], keywords: ["販売", "販売url", "購入先", "外部販売", "販売ページ", "値段", "価格"], uniqueKeywords: ["販売url", "購入先", "外部販売"], priority: 90, actionId: EDITOR_HELP_ACTION_IDS.externalSalesFocus, source: "editor", relatedIntents: ["paywall.insert"] }),
  entry({ intent: "external.links", title: "作品末尾に外部リンクを表示する", answer: "「デザイン・公開設定」の外部リンク名とURLに、Kindle・note・講座・問い合わせ先などを設定できます。安全なhttps URLを入力し、保存後のPreviewで作品末尾の表示を確認してください。", phrases: ["外部リンクを追加したい", "作品の最後にリンクを載せたい", "問い合わせurlを載せたい"], keywords: ["外部リンク", "問い合わせ", "作品末尾", "kindleリンク"], uniqueKeywords: ["外部リンク", "作品末尾"], priority: 88, source: "editor" }),
  entry({ intent: "chapter.heading", title: "チャプター見出しサイズを変える", answer: "現在のローカルEditorでは「デザイン・公開設定」のチャプター見出しサイズから、小・標準・大を一括選択できます。各チャプター開始ページの見出しに反映されるため、Previewで全章を確認してください。", phrases: ["チャプター見出しを変えたい", "章見出しを大きくしたい", "章タイトルのサイズを変えたい"], keywords: ["チャプター見出し", "章見出し", "章タイトルサイズ"], uniqueKeywords: ["チャプター見出し", "章見出し"], priority: 89, source: "editor" }),
  entry({ intent: "author.profile", title: "作者プロフィールを設定する", answer: "Editorの基本情報で作者名・作者ハンドル・自己紹介・ホームページ・X・noteを設定できます。作者ページ全体の公開設定やプロフィール画像は設定画面で管理します。", phrases: ["作者プロフィールを変えたい", "自己紹介を載せたい", "作者ページを設定したい"], keywords: ["作者プロフィール", "作者ハンドル", "自己紹介", "作者ページ"], uniqueKeywords: ["作者プロフィール", "作者ハンドル", "作者ページ"], priority: 88, source: "editor" }),
  entry({ intent: "book.duplicate", title: "作品を複製する", answer: "作品一覧で対象作品の「複製」を選ぶと、元の作品を残したままコピーを作成できます。複製後は新しい作品のタイトルと公開URLを確認してから保存・公開してください。", phrases: ["作品を複製したい", "本をコピーしたい", "同じ作品から作りたい"], keywords: ["複製", "作品コピー", "本をコピー"], uniqueKeywords: ["複製", "作品コピー"], priority: 87, source: "editor" }),
  entry({ intent: "pricing", title: "料金プランを確認する", answer: "現在の無料・出版・運用プランの違いは料金ページで確認できます。将来予定ではなく、料金ページに表示されている条件を基準にしてください。", phrases: ["料金を知りたい", "プランを比較したい", "いくらかかる"], keywords: ["料金", "プラン", "費用", "いくら"], uniqueKeywords: ["料金", "費用"], priority: 85, route: "/pricing", source: "pricing" }),
  entry({ intent: "help", title: "詳しい使い方を見る", answer: "基本的な原稿作成・表紙設定・公開の流れはHelpページでも確認できます。この検索Helpでは、やりたい操作を短い言葉で入力すると該当する案内を表示します。", phrases: ["使い方を見たい", "ヘルプページを開きたい", "操作方法を知りたい"], keywords: ["ヘルプ", "使い方", "操作方法"], uniqueKeywords: ["ヘルプ"], priority: 84, route: "/help", source: "help" }),
  entry({ intent: "use.cases", title: "活用事例を見る", answer: "小説・教材・作品集・お店の案内など、WebBookMakerの使い方は活用事例ページで確認できます。Editorの操作手順ではなく、どんな作品に向くかを知りたいときに利用してください。", phrases: ["活用事例を見たい", "何に使えるか知りたい", "用途を知りたい"], keywords: ["活用事例", "使い道", "用途", "ユースケース"], uniqueKeywords: ["活用事例", "ユースケース"], priority: 83, route: "/use-cases", source: "help" }),
  entry({ intent: "unsupported.ai-rewrite", title: "AIによる文章リライトは未対応", answer: "現在、AIが本文を自動で書き換えるリライト機能はありません。Smart Formatは文章内容を変えず、見出し・段落・目次・ページ構成だけを整えます。", phrases: ["aiで文章を書き直したい", "aiリライトしたい", "文章をaiで直したい"], keywords: ["aiリライト", "aiで書き直す"], uniqueKeywords: ["aiリライト"], priority: 100, source: "help", unsupported: true, relatedIntents: ["smart.format"] }),
  entry({ intent: "unsupported.ai-generate", title: "AIによる文章生成は未対応", answer: "現在、AIに本文や章タイトルを生成させる機能はありません。用意した原稿を貼り付けるか読み込み、必要に応じてSmart Formatで構造を整えてください。", phrases: ["aiで文章を作りたい", "aiに書いてほしい", "文章を自動生成したい"], keywords: ["ai生成", "自動生成", "aiに書いて"], uniqueKeywords: ["ai生成"], priority: 100, source: "help", unsupported: true, relatedIntents: ["manuscript.paste"] }),
  entry({ intent: "unsupported.drag-reorder", title: "ドラッグによるブロック並べ替えは未対応", answer: "現在、本文ブロックをドラッグ＆ドロップして自由に並べ替える機能はありません。画像ファイルの挿入にはドラッグ＆ドロップを使えますが、既存ブロックの順序変更とは別です。", phrases: ["ブロックをドラッグで並べ替えたい", "段落をドラッグ移動したい"], keywords: ["ドラッグ並べ替え", "ブロック移動"], uniqueKeywords: ["ドラッグ並べ替え"], priority: 100, source: "help", unsupported: true }),
  entry({ intent: "unsupported.redo", title: "Redoは未対応", answer: "現在、一般的なRedo機能はありません。Smart Format直後の「整形前に戻す」は1回だけ利用できますが、その取り消しを再実行する機能ではありません。", phrases: ["redoしたい", "やり直しをやり直したい", "取り消しを戻したい"], keywords: ["redo", "リドゥ"], uniqueKeywords: ["redo", "リドゥ"], priority: 100, source: "help", unsupported: true, relatedIntents: ["smart.undo"] }),
  entry({ intent: "unsupported.search-replace", title: "検索・置換は未対応", answer: "現在、作品全体を対象にした検索・一括置換機能はありません。ブラウザのページ内検索は表示中の文字を探せますが、本文の一括置換は行いません。", phrases: ["検索置換したい", "一括置換したい", "文字をまとめて置換したい"], keywords: ["検索置換", "一括置換"], uniqueKeywords: ["検索置換", "一括置換"], priority: 100, source: "help", unsupported: true }),
] as const;

export const EDITOR_HELP_COMMON_INTENTS = [
  "image.insert",
  "smart.format",
  "page.break",
  "paywall.insert",
  "preview",
  "publish",
] as const;

export function helpCatalogEntry(intent: string, catalog = EDITOR_HELP_CATALOG) {
  return catalog.find((candidate) => candidate.intent === intent);
}

export function commonHelpEntries(catalog = EDITOR_HELP_CATALOG) {
  return EDITOR_HELP_COMMON_INTENTS.flatMap((intent) => {
    const match = helpCatalogEntry(intent, catalog);
    return match ? [match] : [];
  });
}
