import assert from "node:assert/strict";
import { parseGoogleMapsUrl } from "../src/lib/googleMaps";
import { normalizeMediaDisplaySize } from "../src/lib/bookProject";
const valid = parseGoogleMapsUrl("https://www.google.com/maps/embed?pb=!1m");
assert.equal(valid?.provider, "google_maps");
const place = parseGoogleMapsUrl("https://www.google.com/maps/search/Tokyo");
assert.equal(place?.provider, "google_maps");
assert.match(place?.embedUrl || "", /output=embed/);
const coordinates = parseGoogleMapsUrl("https://www.google.co.jp/maps/@33.3042331,130.5552312,15z");
assert.equal(coordinates?.provider, "google_maps");
assert.match(coordinates?.embedUrl || "", /q=33\.3042331%2C130\.5552312/);
assert.match(coordinates?.embedUrl || "", /z=15/);
const officialEmbed = parseGoogleMapsUrl("https://www.google.co.jp/maps/embed?pb=!1m");
assert.equal(officialEmbed?.embedUrl, "https://www.google.com/maps/embed?pb=!1m");
assert.equal(normalizeMediaDisplaySize(undefined), "medium");
assert.equal(normalizeMediaDisplaySize("small"), "small");
assert.equal(normalizeMediaDisplaySize("large"), "large");
for (const value of ["http://www.google.com/maps", "https://evil.example/maps", "javascript:alert(1)", "data:text/html,<iframe>", "https://www.google.com/other"]) assert.equal(parseGoogleMapsUrl(value), null);
console.log("Google Maps URL validation: PASS");
