import assert from "node:assert/strict";
import { parseGoogleMapsUrl } from "../src/lib/googleMaps";
import { normalizeMediaDisplaySize } from "../src/lib/bookProject";
import { contentBlocksFromLegacy, contentBlocksToRawText, extractChaptersFromText, createColumnsBlock, type BookContentBlock } from "../src/lib/bookProject";
import { insertMapBlockAtAnchor } from "../src/lib/inlineContentBlocks";
import { buildReaderPages } from "../src/lib/paginateText";
import { normalizeMapAlignment, parseInlineMapToken } from "../src/lib/mapLayout";
import { createEditorHistory } from "../src/lib/editorHistory";
const valid = parseGoogleMapsUrl("https://www.google.com/maps/embed?pb=!1m");
assert.equal(valid?.provider, "google_maps");
const place = parseGoogleMapsUrl("https://www.google.com/maps/search/Tokyo");
assert.equal(place?.provider, "google_maps");
assert.match(place?.embedUrl || "", /output=embed/);
const coordinates = parseGoogleMapsUrl("https://www.google.co.jp/maps/@33.3042331,130.5552312,15z");
assert.equal(coordinates?.provider, "google_maps");
assert.match(coordinates?.embedUrl || "", /q=33\.3042331%2C130\.5552312/);
assert.match(coordinates?.embedUrl || "", /z=15/);
const officialEmbed = parseGoogleMapsUrl("https://www.google.co.jp/maps/embed?pb=!1m");
assert.equal(officialEmbed?.embedUrl, "https://www.google.com/maps/embed?pb=!1m");
assert.equal(normalizeMediaDisplaySize(undefined), "medium");
assert.equal(normalizeMediaDisplaySize("small"), "small");
assert.equal(normalizeMediaDisplaySize("large"), "large");
for (const value of ["http://www.google.com/maps", "https://evil.example/maps", "javascript:alert(1)", "data:text/html,<iframe>", "https://www.google.com/other"]) assert.equal(parseGoogleMapsUrl(value), null);
console.log("Google Maps URL validation: PASS");

assert.equal(normalizeMapAlignment(undefined), "center");
assert.equal(normalizeMapAlignment("position:absolute"), "center");
for (const alignment of ["left", "center", "right"] as const) {
  const map: BookContentBlock = { id: "qa-map", type: "map", ...coordinates!, displaySize: "small", alignment };
  const blocks: BookContentBlock[] = [{ id: "before", type: "text", content: "前の文章。後ろの文章。" }, { id: "end", type: "text", content: "末尾。" }];
  const inserted: BookContentBlock[] = insertMapBlockAtAnchor(blocks, "before", 5, map)!;
  assert.deepEqual(inserted.map((block) => block.id), ["before", "qa-map", "before-tail", "end"]);
  assert.equal(inserted.filter((block) => block.type === "text").map((block) => block.content).join(""), "前の文章。後ろの文章。末尾。");
  assert.equal(insertMapBlockAtAnchor(blocks, "stale-id", 0, map), null, "a stale anchor never appends at the end");
  const legacy = contentBlocksFromLegacy(contentBlocksToRawText(inserted), []);
  const legacyMap = legacy.find((block) => block.type === "map");
  assert.equal(legacyMap?.alignment, alignment);
  assert.equal(legacyMap?.displaySize, "small");
  assert.equal(legacyMap?.embedUrl, coordinates?.embedUrl);
  const history = createEditorHistory(inserted);
  const resized = inserted.map((block) => block.type === "map" ? { ...block, displaySize: "large" as const } : block);
  history.record(resized);
  assert.deepEqual(history.undo(), inserted);
  assert.deepEqual(history.redo(), resized);
  const pages = buildReaderPages({ chapters: extractChaptersFromText(contentBlocksToRawText(inserted), "本文", inserted), images: [], contentBlocks: inserted, charactersPerPage: 380, tableOfContentsItemsPerPage: 6 });
  const textPages = pages.filter((page) => page.kind === "text");
  const inlineMaps = textPages.flatMap((page) => page.paragraphs.map(parseInlineMapToken).filter(Boolean));
  assert.equal(inlineMaps.length, 1);
  assert.equal(inlineMaps[0]?.alignment, alignment);
  assert.equal(inlineMaps[0]?.embedUrl, coordinates?.embedUrl);
  assert.equal(pages.filter((page) => page.kind === "map").length, 0, "Small must not reserve a whole page");
  assert.equal(textPages.length, 1, "short surrounding text and Small share one page");
  const boundaryBlocks: BookContentBlock[] = [{ id: "long", type: "text", content: "本文".repeat(170) }, map, { id: "tail", type: "text", content: "続き。" }];
  const boundaryPages = buildReaderPages({ chapters: extractChaptersFromText(contentBlocksToRawText(boundaryBlocks), "本文", boundaryBlocks), images: [], contentBlocks: boundaryBlocks, charactersPerPage: 380, tableOfContentsItemsPerPage: 6 });
  assert.equal(boundaryPages.filter((page) => page.kind === "text").flatMap((page) => page.paragraphs).filter((paragraph) => parseInlineMapToken(paragraph)).length, 1, "boundary map remains atomic and unique");
  const columns = createColumnsBlock();
  columns.left.blocks = [blocks[0] as Extract<BookContentBlock, { type: "text" }>];
  const nested: BookContentBlock[] = insertMapBlockAtAnchor([columns], "before", 5, map)!;
  assert.equal(nested[0].type === "columns" && nested[0].left.blocks[1].id, "qa-map");
}
console.log("Google Maps layout / anchor / history / persistence / pagination: PASS");
